creditApp/urls.py
from django.urls import path
from . import views

app_name = 'creditApp'

urlpatterns =[
    path('',views.get_user,name='users'),
    path('<int:id>',views.get_individual,name='individual'),
]

creditmanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from creditApp import views
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homePage,name="Home"),
    path('users/',include('creditApp.urls')),
    path('transaction/',views.creatTransaction,name='transaction'),
    path('history/', views.history,name='history')
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

creditApp/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class User_table(models.Model):

    username = models.CharField(max_length=200)
    email = models.EmailField()
    currentCredit = models.IntegerField()
    date_added = models.DateTimeField(default=datetime.now , blank= True)
    id = models.AutoField(primary_key=True)
    image = models.ImageField(upload_to="photos/%Y/%m/%d")

    def __str__(self):
        return self.username
    

class Transaction_table(models.Model):
    Transfer_from = models.ForeignKey(User_table, on_delete=models.CASCADE, related_name='from_user')
    Transfer_to = models.ForeignKey(User_table, on_delete = models.CASCADE , related_name='to_user')
    date = models.DateField(default=datetime.now , blank=True)
    credit= models.PositiveIntegerField()

    

    def __str__(self):
        return str(self.Transfer_from)

creditApp/forms.py
from django.forms import ModelForm
from django import forms
from .models import User_table,Transaction_table


class transactForm(ModelForm):
    class Meta:
        model = Transaction_table
        fields = ['Transfer_from','Transfer_to','credit']
        # widgets = {
        #     'trans_from': forms.TextInput(attrs={'class':'input'}),
        #     'trans_to': forms.TextInput(attrs={'class':'input'}),
        

creditApp/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import User_table
from.models import Transaction_table
from .forms import transactForm
# from django.http import HttpResponse
# Create your views here.

def homePage(request):

    return render(request,"creditApp/home.html")


def get_user(request):
    user_details = User_table.objects.all()
    context = {
        'user_details': user_details
    }
    return render(request, 'creditApp/users.html', context=context)    



def  get_individual(request,id):
    individual = get_object_or_404(User_table,pk=id)
    
    context={
        'individual': individual
    }
    return render(request,'creditApp/individual.html',context=context)


def creatTransaction(request):
    form = transactForm()
    global is_error
    is_error =0
   
    if request.method == 'POST':
        form = transactForm(request.POST)
        # print("returning {}".format(request.POST.get('trans_from')))
        
        if (request.POST.get('Transfer_from') != request.POST.get('Transfer_to')):
            if form.is_valid():
                form.save()
                # getting the fromuserin the post dict.

                # username = form_details.cleaned_data.get("from_trans")
                username = request.POST.get('Transfer_from')

                # getting the userto name from the post dict

                # username_to =form_details.cleaned_data.get("to_trans") 
                username_to = request.POST.get('Transfer_to')
                #  getting the credit being passed by the from user in post dict
                # amount = form_details.cleaned_data.get('currentCredit')
                # print("Printing the value {} and {}".format(username,username_to))
                # print("printing the post %5s" % request.POST)
                

                amount= request.POST.get('credit')
            
                    # this gets the current current of the the to user.
                from_user= User_table.objects.get(id = username)
                from_user_credit= from_user.currentCredit
                print(from_user_credit)


                to_user = User_table.objects.get(id=username_to)
                to_user_credit = to_user.currentCredit

                # option_from = Transaction_table.objects.get('trans_from'==username)
                # option_to = Transaction_table.objects.get('trans_to'== username_to)

                new_userto_credit = int(to_user_credit) + int(amount) # new credit for the to user
                new_userfrom_credit = int(from_user_credit) - int(amount) # new credit to from user

                # updating the new credting to from user
                upadate_userfrom = User_table.objects.get(id=username)
                upadate_userfrom.currentCredit = new_userfrom_credit
                upadate_userfrom.save()

                # updating the new credit to the to user
                upadate_userto = User_table.objects.get(id =username_to)
                upadate_userto.currentCredit = new_userto_credit
                upadate_userto.save()
                is_error=0 # sets the error value to false when there is no error.
               
                return redirect('/')
           
        is_error =1 # this is to set the error value to True when the names are the same.

    context={
        'form':form,
        'is_error': is_error
    }   
    print(is_error)
    return render(request,'creditApp/transaction.html',context=context )



def history(request):
    
    transact_details= Transaction_table.objects.all()
 
    context = {
        'transact_details': transact_details
    }

    return render(request,'creditApp/history.html',context=context)



        

creditApp/templates/creditApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'creditApp/main.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% if '/' == request.path %}
    <title>Home</title>
    {% elif 'transaction' in request.path %}
    <title>Transaction</title>
    {% else %}
    <title>Users</title>
    {% endif %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'creditApp/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'creditApp/favicon-32x32.png'%}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'creditApp/favicon.ico'%}">
    <!-- <link rel="icon" type="image/png" sizes="192x192" href="{% static 'creditApp/andriod-chrome-192x192.png'%}"> -->
    <!-- <link rel="icon" type="image/png" sizes="512x512" href="{% static 'creditApp/andriod-chrome-512x512.png'%}"> -->
    <!-- <link rel="manifest" href="{%static 'creditApp/site.webmanifest'%}"> -->
    <link rel="manifest" href="{%static 'creditApp/site.webmanifest'%}">

    <!-- <script
        async
        src="https://unpkg.com/pwacompat"
        crossorigin="anonymous">
    </script> -->
  
</head>

<body>
    <!-- Header 
     <header class="custom_navbar"> -->
      <nav class="navbar  navbar-expand-lg ">
        <div class="container">
        <a class="navbar-brand" href="#" style="font-size: 2vw;">
          Fast Credit
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li   class="nav-item mr-3 ">
              {% if '/' ==  request.path %}
              <a class="nav-link  lead custom-active" href="{% url 'Home' %}">Home <span class="sr-only">(current)</span></a>
             {%else%}
             <a class="nav-link  lead text-info" href="{% url 'Home' %}">Home <span class="sr-only">(current)</span></a>
             {%endif%}
            </li>
            <li  class="nav-item mr-3 ">
              {% if 'transaction' in  request.path %}
              <a class="nav-link lead custom-active " href="{% url 'transaction' %}">Transfer</a>
             {%else%}
             <a class="nav-link lead text-info " href="{% url 'transaction' %}">Transfer</a>
             {%endif%}
              
            </li>
            <li class="nav-item mr-3 ">
              {% if 'users' in  request.path %}
               <a class="nav-link lead custom-active " href="{% url 'creditApp:users' %}" >Users</a>
              {%else%}
              <a class="nav-link lead  text-info" href="{% url 'creditApp:users' %}" >Users</a>
              {%endif%}
            </li>
          
          </ul>
        </div>
      </div>
      </nav>
      <head>
      <div class="banner" style="margin-top: 8px; width:100%;">
        <span class="lead" style="font-size:3vw;font-family: 'Dancing Script', cursive;"> Transfer Faster </span>
    </div>
  </head>  
    <!-- </header> -->

   

    <!-- Block content -->

    {% block content %}





    
    {% endblock %}

</body>
</html>

creditApp/templates/creditApp/history.html
{%extends 'creditApp/base.html'%}

{% block content %}
<div class="container bg-light" style="margin-left: 2%;">
<div class="jumbotron  bg-light "  style="border-radius: 30px;padding: 0px 15px 0px 15px; margin:2% 15% 2% 1%; box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.7);z-index: 1;">
  <div class="row">
<div class="col-md-10" style="margin: 0% 20% 0% 1%; ">
<table class="table" style="margin-top: 2%;" >
    <thead class="thead-light " style="font-size: 2vw;padding-top: 1%; border-radius: 36px;">
      <tr>
        <th scope="col">#</th>
        <th scope="col">From</th>
        <th scope="col">To</th>
        <th scope="col">Credit </th>
        <th scope="col"> Date </th>
      </tr>
    </thead>
    <tbody style="font-size: 2vw; font-family: 'Dancing Script', cursive;">
        {% for transact in transact_details %}
      <tr class="text-dark ">
        <th scope="row" class=" badge badge-pill badge-dark ">{{transact.id}}</th>
        <td>{{transact.Transfer_from.username}}</td>
        <td>{{transact.Transfer_to.username}}</td>
        <td>{{transact.credit}}</td>
        <td>{{ transact.date}}</td>
      </tr>
      {%endfor %}
    </tbody>
  </table>
</div>
</div>
</div>
</div>
{% endblock %}

creditApp/templates/creditApp/home.html
{% extends 'creditApp/base.html'%}
{%load static%}
<!-- block content  -->
{% block content %}

<div class="jumbotron bg-color " style="margin-top: -20px;">
    <div  class="row" style="margin-top: -3%;margin-bottom: 14%;">

        <div class="col-ms-12" >
                 <div class="card-deck">
                    <div class="card" >
                        <img style="width: 50%; align-self: center;" src="{% static 'creditApp/avatar.jpg'%}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title lead text-dark" style="font-size: 2vw;">Users</h5>
                            <p class="card-text">See all the <em><b>users</b></em> available<br>
                            </p>
                            <a href="{%url 'creditApp:users' %}" class="btn btn-primary btn-outline-info text-white lead">Users</a>
                         </div>
                    </div>
       
            <div class="card" >           
                        <img style="width: 50%;align-self: center;" src="{% static 'creditApp/stock3cp.png'%}" class="card-img-top" alt="...">

                        <div class="card-body">
                            <h5 class="card-title lead text-dark" style="font-size: 2vw;">Transfer</h5>
                            <p class="card-text">Make transfers with <em><b>love</b></em>
                            </p>
                             <a href="{% url 'transaction' %}" class="btn btn-primary btn-outline-info text-white lead">Transfer</a>
                        </div>
            </div>

            <div class="card">
                    <div style=" background-color: whitesmoke;align-items: center;">

                        <div>
                            <img style="border-radius: 50%; width: 50%;" src="{% static 'creditApp/credithistory2.png'%}" class="card-img-top" alt="...">
                        </div>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title lead text-dark" style="font-size: 2vw;">History</h5>
                        <p class="card-text">We've got all your transactions in a safe palce for you.<br>
                            Have a look at all your credit <em><b>history!</b></em>
                        </p>
                        <a href="{% url 'history' %}" class="btn btn-primary btn-outline-info text-white lead">Credit History</a>
                    </div>
                </div>
            </div>    
        </div>
    </div>
</div>
<!-- 
<footer class=" banner bg-dark text-light justify-content-center" style="position: fixed; height: 72px; width: 100%;margin-top: -3%;">


    
    
    </footer> 
-->

    <footer class=" container mt-4 ">
        <div class=”row”>
        <div class=”col-md”>
        <p style="text-align: center; align-self: center;" class="mx-auto" >   
             <span class="" style="text-align: center;margin-top: 10%;" >
            copyright<span>&COPY;</span>2020-2021 &nbsp; 
             </span><br>
             <span class="text-dark font-weight-bold">Design by Mark Owusu</span><br>
             <span class="font-weight-light">Web developer intern @ The Sparks Foundation.</span>
      </p>
        </div>
        </div>
       </footer>

{% endblock %}

creditApp/templates/creditApp/individual.html
{% extends 'creditApp/base.html'%}
{% block content %}

<div class="jumbotron  bg-dark " style="margin: -2% 0% -3% 0%;">
    <div class="card mx-auto" style="width: 20rem;margin: -2% 0% -2% 0%;border-radius: 10%; ">
        <div class="rec-circle mx-auto mt-2">
            <img  src="{{individual.image.url}}" class="card-img-top " alt="">
        </div>
        <div class="card-body">
          <h5 class="card-title text-dark " >User Name: <span class="font-weight-bolder">{{individual.username}}</span></h5>
          <h6 class="card-subtitle mb-2 text-muted">Entry Date: <span  class="font-weight-bolder">{{individual.date_added}}</span></h6>
          <h6 class="card-subtitle mb-2 text-muted">Email:  <span class="font-weight-bolder">{{individual.email}}</span></h6>
          {% if individual.currentCredit <= 0 %}
          <p class="card-text text-danger ">Current Credit: <span  class="font-weight-bolder" >{{individual.currentCredit}}</span></p>
          {% else %}
          <p class="card-text text-success ">Current Credit: <span  class="font-weight-bolder" >{{individual.currentCredit}}</span></p>
          {%endif%}
          <a href="{% url 'creditApp:users' %} " class="btn btn-primary mx-4 rounded-pill lead ">Go Back</a>
          <a href="# " class="btn btn-primary mx-4 rounded-pill lead invisible">Transfer to another User!</a>

        </div>
      </div>

</div>
{% endblock %}

creditApp/templates/creditApp/transaction.html
{% extends 'creditApp/base.html'%}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<div class="jumbotron bg-dark mr-4 ml-4 rounded-circle transact-bg" >
   
    <div class="row row-transact">
        <div class="col-8">
            {%  if is_error %}
            <p class="btn text-light bg-danger lead btn-outline-light " style="margin: 1% -15% 0% 50%;font-weight: 5vw;">Not allowed</p>
            {% endif %}
 <form  style="margin: 1% -15% 0% 50%;"  action=''  method="POST">
     {%csrf_token%}
      {{form|crispy}} 
      {% for error in form.error %}
      <p class="text-danger">{{error}}</p>
      {%endfor %}
      <button type="submit" class="btn btn-ms btn-primary btn-outline-light badge-pill "  >Submit</button>
    </form>
    </div>
</div>
</div>
</div>



{% endblock %}

creditApp/templates/creditApp/users.html
{% extends 'creditApp/base.html'%}
{% load static %}

{%block content %}
  <div class="container bg-light">
  <div class="jumbotron  bg-light " style="border-radius: 35px;padding: 0px 20px 0px 20px; margin: 3% 0% 0% 0%;box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.7);z-index: 1;">
    <div class="row">
      <div class="col-md-8 " style="margin: 0% 17% 0% 10%; ">

    <table class="table " style="margin-top: 2%;" >
      <thead class="thead-light" style="font-size: 2vw;padding-top: 1%;">
        <tr class=" text-dark">
          <th scope="col">#</th>
          <th scope="col">User Name</th>
          <th scope="col">Credit</th>
          <!-- <th scope="col">Email </th> -->
          <th scope="col" >Action</th>
        </tr>
      </thead>
      <tbody style="font-size: 2vw; font-family: 'Dancing Script', cursive;">
        {% for user in user_details %}
        <tr class="text-dark ">
          <th scope="row" class="badge badge-dark rounded-circle  ">{{user.id}}</th>
          <td class="ml-1">{{user.username}}</td>
          <td>{{user.currentCredit}}</td>
          <!-- <td style="font-weight: 14vw;">{{user.email}}</td> -->
          <td> <a class="btn btn-secondary btn-outline-info text-light rounded-pill" href="{% url 'creditApp:individual' user.id %}">View</a></td>

          <!-- Remember that passing a template varible in a url tag does not need double-curly but just specify like the below eg => { url 'appname:name_of url_in_apps.urls' template_variable-->
        </tr>
        {% endfor %}

   
       
      </tbody>
    </table>
    </div>
  </div>
  </div>
</div>


{%endblock%}